import org.gradle.api.tasks.bundling.Jar
import org.gradle.jvm.toolchain.JavaLanguageVersion

plugins {
	id 'java'
	id 'maven-publish'
	id "xyz.wagyourtail.unimined" version "1.3.14" apply false
}

subprojects {
	apply plugin: "xyz.wagyourtail.unimined"
	apply plugin: "java"
	apply plugin: 'maven-publish'

	archivesBaseName = project.name

	version = rootProject.mod_version
	group = rootProject.maven_group

	configurations {
		modCompileOnly
		compileOnly.extendsFrom modCompileOnly
		modApi
		api.extendsFrom modApi
	}

	unimined.minecraft(sourceSets.main) {
		version rootProject.minecraft_version

		mappings {
			intermediary()
			yarn(rootProject.yarn_mappings)
			devNamespace "yarn"
			devFallbackNamespace "intermediary"
		}

		minecraftForge {
			loader forge_version
			if (project.hasProperty("mixins")){
				mixinConfig(project.getProperties().get("mixins").split(","))
			}
			var at = project.file("src/main/resources/META-INF/accesstransformer.cfg")
			if (at.exists()){
				accessTransformer(at)
			}

		}

		mods {
			remap(configurations.modCompileOnly) {
				catchAWNamespaceAssertion()
			}

			remap(configurations.modApi)

			// this is basically just a shortcut for `remap(configurations.modImplementation)`
			modImplementation {
				// you can do this is mods have the wrong access widener mapping, but it may break runs
				catchAWNamespaceAssertion()
			}
		}
	}

	tasks.withType(JavaCompile).configureEach {
		it.options.encoding = 'UTF-8'
		it.options.getRelease().set(17)
	}

	processResources {
		inputs.property "version", project.version

		filesMatching("META-INF/mods.toml") {
			expand "version": project.version
		}
	}

	java {
		withSourcesJar()
	}

	publishing {
		publications {
			mavenJava(MavenPublication) {
				// add all the jars that should be included when publishing to maven
				from components.java
			}
		}
		setupRepositories(repositories)
	}
}

void setupRepositories(RepositoryHandler repositories) {
	//repositories.mavenLocal() // uncomment for testing
	def ENV = System.getenv()
	repositories.maven {
		url System.getenv("local_maven_url")
	}
}
