modLoader="javafml"
license="Apache-2.0"
loaderVersion="[40,)"
issueTrackerURL="https://github.com/Trinsdar/Terraform-Reforged/issues"

[[mods]]
modId="terraform_biome_remapper"
version="${version}"
displayName="Terraform Biome Remapper Reforged"
displayURL="https://github.com/Trinsdar/Terraform-Reforged"
credits="Terraform team for creating the original api."
authors="Trinsdar"
description='''A Port of the Terraform api to forge'''
[[dependencies.terraform_biome_remapper]]
modId="forge"
mandatory=true
versionRange="[40.1.0,)"
ordering="AFTER"
side="BOTH"
[[dependencies.terraform_biome_remapper]]
modId="minecraft"
mandatory=true
versionRange="[1.18.2,)"
ordering="AFTER"
side="BOTH"
